language: node_js
node_js:
  - "node"
  - 8
before_install:
  - npm install -g npm@latest
  - npm install -g codecov
  - npm install -g nyc
after_install:
  - ls node_modules/mocha
script:
  - npm run test
  - npm run report-coverage
