language: node_js
node_js:
  - "node"
  - 10
before_install:
  - npm install -g npm@latest
  - npm install -g nyc
after_install:
  - ls node_modules/mocha
script:
  - npm run test:isPrime
  - bash <(curl -s https://codecov.io/bash) -c -F isPrime
  - npm run test:getOdd
  - bash <(curl -s https://codecov.io/bash) -c -F getOdd
